language: node_js
node_js:
  - "11"
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
before_install:
  - 'nvm install-latest-npm'
install:
  - 'if [ -n "${PACKAGE-}" ]; then cd "packages/${PACKAGE}"; fi'
  - 'if [ "${TRAVIS_NODE_VERSION}" = "0.6" ] || [ "${TRAVIS_NODE_VERSION}" = "0.9" ]; then nvm install --latest-npm 0.8 && npm install && nvm use "${TRAVIS_NODE_VERSION}"; else npm install; fi;'
  - 'if [ -n "${ESLINT}" ]; then npm install --no-save "eslint@${ESLINT}"; fi'
script:
  - 'if [ -n "${PREPUBLISH-}" ]; then npm run pretravis && npm run prepublish && npm run posttravis; elif [ -n "${LINT-}" ]; then npm run lint; else npm run travis; fi'
sudo: false
env:
  matrix:
    - 'TEST=true ESLINT=5 PACKAGE=eslint-config-airbnb-base'
    - 'TEST=true ESLINT=5 PACKAGE=eslint-config-airbnb'
    - 'TEST=true ESLINT=4 PACKAGE=eslint-config-airbnb-base'
    - 'TEST=true ESLINT=4 PACKAGE=eslint-config-airbnb'
matrix:
  fast_finish: true
  include:
    - node_js: "lts/*"
      env: PREPUBLISH=true ESLINT=5 PACKAGE=eslint-config-airbnb-base
    - node_js: "lts/*"
      env: PREPUBLISH=true ESLINT=5 PACKAGE=eslint-config-airbnb
    - node_js: "lts/*"
      env: PREPUBLISH=true ESLINT=4 PACKAGE=eslint-config-airbnb-base
    - node_js: "lts/*"
      env: PREPUBLISH=true ESLINT=4 PACKAGE=eslint-config-airbnb
    - node_js: "lts/*"
      env: LINT=true
  exclude:
    - node_js: "5"
      env: TEST=true ESLINT=5 PACKAGE=eslint-config-airbnb-base
    - node_js: "5"
      env: TEST=true ESLINT=5 PACKAGE=eslint-config-airbnb
    - node_js: "4"
      env: TEST=true ESLINT=5 PACKAGE=eslint-config-airbnb-base
    - node_js: "4"
      env: TEST=true ESLINT=5 PACKAGE=eslint-config-airbnb
  allow_failures:
    - node_js: "9"
    - node_js: "7"
    - node_js: "5"
    - env: PREPUBLISH=true ESLINT=5 PACKAGE=eslint-config-airbnb-base
    - env: PREPUBLISH=true ESLINT=5 PACKAGE=eslint-config-airbnb
    - env: PREPUBLISH=true ESLINT=4 PACKAGE=eslint-config-airbnb-base
    - env: PREPUBLISH=true ESLINT=4 PACKAGE=eslint-config-airbnb
